# Site settings
title: Javier Díaz
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Personal, Portfolio, UX, Design
author: Javo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
